# Generated by contracts/v2/product_rpc_capability_policy.py.
# Do not edit by hand.

from typing import Literal

CurrentOwner = Literal["pythonBff", "goSidecar", "wpfHost", "pythonWorker"]

PRODUCT_RPC_METHODS_BY_CURRENT_OWNER = {
    "pythonBff": (
        "command.list",
        "command.run",
        "contentProfile.commit",
        "contentProfile.delete",
        "contentProfile.load",
        "data.applyImport",
        "data.export",
        "data.generateTemplate",
        "data.previewImport",
        "file.applyHostChange",
        "file.saveHostFile",
        "file.token",
        "formula.draft.validate",
        "formula.preview",
        "formula.validate",
        "gridState.get",
        "gridState.save",
        "insights.dashboardQueryLimits",
        "insights.deleteDashboardWorkspace",
        "insights.executeDashboardQuery",
        "insights.listDashboards",
        "insights.panelManifest",
        "insights.readDashboardWorkspace",
        "insights.saveDashboardDraft",
        "interface.commit",
        "interface.delete",
        "interface.list",
        "interface.load",
        "path.registerExportTarget",
        "path.registerImportSource",
        "path.requestExportTarget",
        "path.requestImportSource",
        "path.resolveGrant",
        "plugin.cancelInstall",
        "plugin.cancelTask",
        "plugin.commitInstall",
        "plugin.describeAction",
        "plugin.getTask",
        "plugin.inspectInstall",
        "plugin.listAudit",
        "plugin.listCatalog",
        "plugin.listPendingCleanup",
        "plugin.resolveFile",
        "plugin.resolveInteraction",
        "plugin.rollback",
        "plugin.setEnabled",
        "plugin.startAction",
        "plugin.uninstall",
        "plugin.upgrade",
        "recordDocumentLink.commit",
        "recordDocumentLink.delete",
        "recordDocumentLink.list",
        "recordDocumentLink.repair",
        "relation.applyDelta",
        "relation.createTarget",
        "relation.updateSingle",
        "schema.delete",
        "schema.table.create",
        "settings.readShared",
        "shortcut.delete",
        "shortcut.launch",
        "shortcut.list",
        "shortcut.save",
        "system.handshake",
        "table.applyPaste",
        "table.previewPaste",
        "task.cancel",
        "task.create",
        "task.status",
        "version.compare",
        "version.create",
        "version.delete",
        "version.list",
        "version.promote",
        "version.save",
    ),
    "goSidecar": (
        "events.reconcile",
        "field.settings.describe",
        "file.list",
        "history.applyRestore",
        "history.previewRestore",
        "history.read",
        "lookup.list",
        "lookup.query",
        "lookup.valuePage",
        "mutation.apply",
        "mutation.preview",
        "preset.delete",
        "preset.list",
        "preset.save",
        "query.cursorFetch",
        "query.cursorOpen",
        "query.page",
        "query.readRows",
        "query.selectionOpen",
        "query.validateSnapshot",
        "query.view",
        "relation.inspectPair",
        "relation.previewDelta",
        "relation.searchTargets",
        "schema.describe",
        "schema.getTable",
        "schema.list",
    ),
    "wpfHost": (
        "settings.readDevice",
        "settings.saveDevice",
    ),
    "pythonWorker": (),
}

PRODUCT_EVENT_TOPICS_BY_CURRENT_OWNER = {
    "pythonBff": (
        "plugin.catalog.changed",
        "plugin.file.requested",
        "plugin.interaction.requested",
        "plugin.task.changed",
    ),
    "goSidecar": (
        "data.changed",
        "realtime.recovered",
    ),
    "wpfHost": ("task.changed",),
    "pythonWorker": (),
}


def current_owner_methods(owner: CurrentOwner) -> tuple[str, ...]:
    try:
        return PRODUCT_RPC_METHODS_BY_CURRENT_OWNER[owner]
    except KeyError as error:
        raise ValueError(f"unknown current owner: {owner}") from error


def current_owner_topics(owner: CurrentOwner) -> tuple[str, ...]:
    try:
        return PRODUCT_EVENT_TOPICS_BY_CURRENT_OWNER[owner]
    except KeyError as error:
        raise ValueError(f"unknown current owner: {owner}") from error
