package schema

import (
	"encoding/json"
	"fmt"
	"math"
	"net/mail"
	"net/url"
	"reflect"
	"regexp"
	"strings"
	"time"

	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
)

const maxSafeWireInteger = int64(1<<53 - 1)

var timeValuePattern = regexp.MustCompile(
	`^(?:[01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](?:\.[0-9]{1,3})?$`,
)
var uuidValuePattern = regexp.MustCompile(
	`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$`,
)

// ValueError is returned when a value doesn't satisfy normalized product
// semantics. Callers add their public request/schema path at the API seam.
type ValueError struct {
	Message      string
	InstancePath string
}

func (e *ValueError) Error() string {
	if e.InstancePath == "" {
		return e.Message
	}
	return e.Message + " at " + e.InstancePath
}

// ValidateFieldValue is the single product-level validator shared by static
// schema defaults and the MutationKernel. PocketBase remains the final storage
// validator, but product-only types and constraints are enforced here.
func ValidateFieldValue(field FieldDefinition, value any) error {
	if value == nil {
		if field.Nullable {
			return nil
		}
		return valueError("value is required")
	}
	dataType := effectiveDataType(field)
	switch dataType {
	case DataTypeShortText, DataTypeLongText, DataTypeRichText,
		DataTypeTime, DataTypeEmail, DataTypeURL, DataTypeUUID,
		DataTypeHash, DataTypeSecret:
		text, ok := value.(string)
		if !ok {
			return valueError("value must be a string")
		}
		switch dataType {
		case DataTypeTime:
			if !timeValuePattern.MatchString(text) {
				return valueError("time must use HH:mm:ss[.fff]")
			}
		case DataTypeEmail:
			address, err := mail.ParseAddress(text)
			if err != nil || address.Address != text {
				return valueError("value must be a valid email address")
			}
		case DataTypeURL:
			parsed, err := url.ParseRequestURI(text)
			if err != nil || parsed.Scheme == "" || parsed.Host == "" {
				return valueError("value must be an absolute URL")
			}
		case DataTypeUUID:
			if !uuidValuePattern.MatchString(text) {
				return valueError("value must be a valid UUID")
			}
		}
	case DataTypeSelect:
		if err := validateSelectValue(field, value, false); err != nil {
			return err
		}
	case DataTypeBoolean:
		if _, ok := value.(bool); !ok {
			return valueError("value must be boolean")
		}
	case DataTypeInteger:
		number, integer, err := numericValue(value)
		if err != nil || !integer || math.Abs(number) > float64(maxSafeWireInteger) {
			return valueError("integer must be a finite safe wire integer")
		}
	case DataTypeFloat, DataTypeDecimal:
		number, _, err := numericValue(value)
		if err != nil || math.IsNaN(number) || math.IsInf(number, 0) {
			return valueError("number must be finite")
		}
	case DataTypeDate:
		text, ok := value.(string)
		if !ok {
			return valueError("date must be a string")
		}
		if _, err := time.Parse("2006-01-02", text); err != nil {
			return valueError("date must use YYYY-MM-DD")
		}
	case DataTypeDateTime:
		text, ok := value.(string)
		if !ok {
			return valueError("dateTime must be a string")
		}
		if _, err := time.Parse(time.RFC3339Nano, text); err != nil {
			return valueError("dateTime must use RFC 3339 with an explicit timezone")
		}
	case DataTypeAutoDate:
		return valueError("autoDate values are generated by the server")
	case DataTypeMultiSelect:
		if err := validateSelectValue(field, value, true); err != nil {
			return err
		}
	case DataTypeJSON, DataTypeGeoJSON:
		if err := validateJSONValue(value); err != nil {
			return err
		}
	case DataTypeList:
		if !isArray(value) {
			return valueError("list value must be a JSON array")
		}
		if err := validateJSONValue(value); err != nil {
			return err
		}
	case DataTypeFile:
		return valueError("attachment defaults and scalar values are not supported")
	case DataTypeRelation:
		// Relation existence and cardinality are validated by MutationKernel
		// against the authoritative target collection.
	case DataTypeGeoPoint:
		if err := validateJSONValue(value); err != nil {
			return err
		}
	case DataTypeLookup, DataTypeFormula:
		return valueError("computed values are generated by the server")
	default:
		return valueError("unsupported product data type")
	}

	if err := validateCommonValueConstraints(field, value); err != nil {
		return err
	}
	if constraint := constraintFor(field, ConstraintJSONSchema); constraint != nil {
		compiled, err := compileJSONSchema(constraint.Schema)
		if err != nil {
			return valueError("stored JSON Schema is invalid")
		}
		if err := compiled.Validate(value); err != nil {
			instancePath := ""
			if validationErr, ok := err.(*jsonschema.ValidationError); ok {
				instancePath = "/" + strings.Join(validationErr.InstanceLocation, "/")
				instancePath = strings.TrimSuffix(instancePath, "/")
			}
			return &ValueError{
				Message:      "value does not satisfy JSON Schema",
				InstancePath: instancePath,
			}
		}
	}
	return nil
}

func ValidateJSONSchema(document map[string]any) error {
	_, err := compileJSONSchema(document)
	return err
}

func compileJSONSchema(document map[string]any) (*jsonschema.Schema, error) {
	if document == nil {
		return nil, fmt.Errorf("JSON Schema must be an object")
	}
	if err := rejectExternalReferences(document); err != nil {
		return nil, err
	}
	compiler := jsonschema.NewCompiler()
	const location = "vibetable://field.schema.json"
	if err := compiler.AddResource(location, document); err != nil {
		return nil, err
	}
	return compiler.Compile(location)
}

func rejectExternalReferences(value any) error {
	switch typed := value.(type) {
	case map[string]any:
		for key, child := range typed {
			if key == "$ref" {
				reference, ok := child.(string)
				if !ok || (!strings.HasPrefix(reference, "#") && reference != "") {
					return fmt.Errorf("external JSON Schema references are not allowed")
				}
			}
			if err := rejectExternalReferences(child); err != nil {
				return err
			}
		}
	case []any:
		for _, child := range typed {
			if err := rejectExternalReferences(child); err != nil {
				return err
			}
		}
	}
	return nil
}

func validateCommonValueConstraints(field FieldDefinition, value any) error {
	if constraint := constraintFor(field, ConstraintRange); constraint != nil {
		number, _, err := numericValue(value)
		if err != nil {
			return valueError("range constraint requires a number")
		}
		if constraint.Min != nil &&
			(number < *constraint.Min || constraint.ExclusiveMin && number == *constraint.Min) {
			return valueError("value is below the allowed minimum")
		}
		if constraint.Max != nil &&
			(number > *constraint.Max || constraint.ExclusiveMax && number == *constraint.Max) {
			return valueError("value is above the allowed maximum")
		}
	}
	text, isText := value.(string)
	if constraint := constraintFor(field, ConstraintLength); constraint != nil && isText {
		length := len([]rune(text))
		if constraint.MinLength != nil && length < *constraint.MinLength {
			return valueError("value is shorter than minLength")
		}
		if constraint.MaxLength != nil && length > *constraint.MaxLength {
			return valueError("value is longer than maxLength")
		}
	}
	if constraint := constraintFor(field, ConstraintPattern); constraint != nil && isText {
		pattern, err := regexp.Compile(constraint.Pattern)
		if err != nil || !pattern.MatchString(text) {
			return valueError("value does not match pattern")
		}
	}
	return nil
}

func validateSelectValue(field FieldDefinition, value any, multiple bool) error {
	constraint := enumConstraint(field)
	if constraint == nil {
		return valueError("select field has no enum constraint")
	}
	values := []any{value}
	if multiple {
		slice, ok := arrayValues(value)
		if !ok {
			return valueError("multiSelect value must be an array")
		}
		values = slice
		if len(values) < constraint.MinSelected {
			return valueError("multiSelect has fewer values than minSelected")
		}
		if constraint.MaxSelected != nil && len(values) > *constraint.MaxSelected {
			return valueError("multiSelect has more values than maxSelected")
		}
	}
	for _, candidate := range values {
		found := false
		for _, option := range constraint.Options {
			if jsonValuesEqual(option.Value, candidate) {
				found = true
				break
			}
		}
		if !found {
			return valueError("select value is not an allowed option")
		}
	}
	return nil
}

func numericValue(value any) (float64, bool, error) {
	switch typed := value.(type) {
	case json.Number:
		number, err := typed.Float64()
		if err != nil {
			return 0, false, err
		}
		integer := !strings.ContainsAny(typed.String(), ".eE")
		if !integer {
			integer = math.Trunc(number) == number
		}
		return number, integer, nil
	case int:
		return float64(typed), true, nil
	case int8:
		return float64(typed), true, nil
	case int16:
		return float64(typed), true, nil
	case int32:
		return float64(typed), true, nil
	case int64:
		return float64(typed), true, nil
	case uint:
		return float64(typed), true, nil
	case uint8:
		return float64(typed), true, nil
	case uint16:
		return float64(typed), true, nil
	case uint32:
		return float64(typed), true, nil
	case uint64:
		if typed > uint64(maxSafeWireInteger) {
			return 0, false, fmt.Errorf("integer exceeds safe wire range")
		}
		return float64(typed), true, nil
	case float32:
		number := float64(typed)
		return number, math.Trunc(number) == number, nil
	case float64:
		return typed, math.Trunc(typed) == typed, nil
	default:
		return 0, false, fmt.Errorf("value is not numeric")
	}
}

func validateJSONValue(value any) error {
	raw, err := json.Marshal(value)
	if err != nil {
		return valueError("value is not valid JSON")
	}
	var decoded any
	decoder := json.NewDecoder(strings.NewReader(string(raw)))
	decoder.UseNumber()
	if err := decoder.Decode(&decoded); err != nil {
		return valueError("value is not valid JSON")
	}
	return nil
}

func isArray(value any) bool {
	_, ok := arrayValues(value)
	return ok
}

func arrayValues(value any) ([]any, bool) {
	reflected := reflect.ValueOf(value)
	if !reflected.IsValid() ||
		(reflected.Kind() != reflect.Slice && reflected.Kind() != reflect.Array) {
		return nil, false
	}
	values := make([]any, reflected.Len())
	for index := range values {
		values[index] = reflected.Index(index).Interface()
	}
	return values, true
}

func jsonValuesEqual(left, right any) bool {
	leftRaw, leftErr := json.Marshal(left)
	rightRaw, rightErr := json.Marshal(right)
	return leftErr == nil && rightErr == nil && string(leftRaw) == string(rightRaw)
}

func valueError(message string) *ValueError {
	return &ValueError{Message: message}
}
